### ISSUE TITLE
A script to upgrade Numaflow version

### ISSUE THREAD

**Issue by whynowy** [numaproj/helm-charts#6]
Needs a script to update the Numaflow manifest templates for version upgrade.

**Comment by th0ger** [comment]
Is this helm chart safe to use, i.e. can it be pinned to specific stable numaflow version?

**Comment by chandankumar4** [comment]
As per conversation with @whynowy for automating a numaflow upgrade is a bit hacky way as there is multiple things needs to be updated like: crd, configmap, deployment specs  or values.yaml, where CRD is straight forward but not for others.
So as part of this issue will be having CRDs update script and helm chart publish via github action.
