### ISSUE TITLE
update to 1.2 numaflow version

### ISSUE THREAD

**Issue by vigith** [numaproj/helm-charts#7]

**Comment by th0ger** [comment]
The new chart version `0.0.2` is not properly released

```bash
$ helm repo add numaflow https://numaproj.io/helm-charts
"numaflow" has been added to your repositories

$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "numaflow" chart repository
Update Complete. ⎈Happy Helming!⎈

$ helm search repo numaflow/numaflow --versions
NAME                    CHART VERSION   APP VERSION     DESCRIPTION
numaflow/numaflow       0.0.1                           A Helm chart for installing Numaflow in Kubernetes

$ helm install numaflow numaflow/numaflow --version "0.0.2" --namespace numaflow-system --create-namespace
Error: INSTALLATION FAILED: chart "numaflow" matching 0.0.2 not found in numaflow index. (try 'helm repo update'): no chart version found for numaflow-0.0.2
```

**Comment by vigith** [comment]
@chandankumar4 please look into this

**Comment by chandankumar4** [comment]
> The new chart version `0.0.2` is not properly released
> 
> ```shell
> $ helm repo add numaflow https://numaproj.io/helm-charts
> "numaflow" has been added to your repositories
> 
> $ helm repo update
> Hang tight while we grab the latest from your chart repositories...
> ...Successfully got an update from the "numaflow" chart repository
> Update Complete. ⎈Happy Helming!⎈
> 
> $ helm search repo numaflow/numaflow --versions
> NAME                    CHART VERSION   APP VERSION     DESCRIPTION
> numaflow/numaflow       0.0.1                           A Helm chart for installing Numaflow in Kubernetes
> 
> $ helm install numaflow numaflow/numaflow --version "0.0.2" --namespace numaflow-system --create-namespace
> Error: INSTALLATION FAILED: chart "numaflow" matching 0.0.2 not found in numaflow index. (try 'helm repo update'): no chart version found for numaflow-0.0.2
> ```

Hey @th0ger  can you try the above steps again, I have resolved the above issue. Thanks

**Comment by th0ger** [comment]
@chandankumar4 Works as expected.
